/*
 * Mckoi Software ( http://www.mckoi.com/ )
 * Copyright (C) 2000 - 2015  Diehl and Associates, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.mckoi.network;

import com.mckoi.util.StyledPrintWriter;
import java.io.PrintStream;
import java.io.PrintWriter;

/**
 * An exception generated when an administration command fails (in
 * com.mckoi.network.NetworkProfile).
 *
 * @author Tobias Downer
 */

public class NetworkAdminException extends Exception {

  private ExternalThrowable external_throwable;
  
  public NetworkAdminException(Message m) {
    super(m.getErrorMessage());
    external_throwable = m.getExternalThrowable();
  }

  public NetworkAdminException(String msg) {
    super(msg);
    external_throwable = null;
  }

  /**
   * Returns an ExternalThrowable if this error was generated by a remote
   * exception, or returns null if this exception is the source.
   */
  public ExternalThrowable getExternalThrowable() {
    return external_throwable;
  }

  /**
   * Prints the error string + stack trace to the print stream.
   */
  public void printAdminError(PrintStream out) {
    printStackTrace(out);
    if (external_throwable != null) {
      out.println("Caused from server exception;");
      out.println(external_throwable.getStackTrace());
    }
  }

  /**
   * Prints the error string + stack trace to the print stream.
   */
  public void printAdminError(PrintWriter out) {
    printStackTrace(out);
    if (external_throwable != null) {
      out.println("Caused from server exception;");
      out.println(external_throwable.getStackTrace());
    }
  }

  /**
   * Prints the error string + stack trace to the print stream.
   */
  public void printAdminError(StyledPrintWriter out) {
    out.printException(this);
    if (external_throwable != null) {
      out.println("Caused from server exception;");
      out.println(external_throwable.getStackTrace());
    }
  }

}
